### ISSUE TITLE
Inflexibility WRT Go source and VFS data locations

### ISSUE THREAD

**Issue by curio77** [aletheia-icu/broccoli#2]
Currently, broccoli must be called from a Go source directory (I call it manually via `go run aletheia.icu/broccoli` and don't use Go's generation feature).  If this is not the case, it errors out with `broccoli: cannot parse package: no buildable Go source files in .`.

Now if the data I want to have broccoli slurp resides somewhere completely else (in my case `../../../../frontend/dist`; making this absolute wouldn't help either), the path ends up in the VFS, which will rarely be desirable.  Because of the requirement to run broccoli from a source directory, I cannot opt to, say, run it from the `dist` directory in the example and have it write a Go file to a completely different directory.

There should be an option to map the given source directories to a (common) prefix that replaces any path implied by the physical location.  For example, I'd like to make the contents of the distant directory referenced above available at the root of the VFS.  If not that, an option to have it strip n levels of directories would help in my case as well.

**Comment by jtorvald** [comment]
Just wanted to post this issue. My dir structure is:
cmd/server/main.go
pkg/websockets
web/js/example.js
web/index.html

With this code in cmd/server/main.go:
//go:generate broccoli -src ../../web/,../../web/js/ -o broccoli -var broccoli -opt -gitignore -include *.html *.js *.css

I also can not access index.html because it's shown as: 
INFO[0000] &{map[../../web/index.html:0xc0000f3490] [../../web/index.html]} 

Also not sure why js/* is not included here.

**Comment by demget** [comment]
@curio77, @jtorvald Just pushed a fix that trims "../" in relative paths. Now this should work:

```go
//go:generate broccoli -src ../../web

func main() {
     f, err := br.Open("web/index.html")
}
```

**Comment by demget** [comment]
> Also not sure why js/* is not included here.

@jtorvald `-include` flag splits args by comma: `*.html,*.js,*.css`. You have a syntax mistake here.

**Comment by jtorvald** [comment]
@demget thanks! In my case I want replace: 
http.FileServer(http.Dir("./web")) 
with broccoli like: 
http.FileServer(broccoli)
If it's possible without changing broccoli, do you have suggestions?

**Comment by demget** [comment]
@jtorvald Yes, that is how it should work.

**Comment by jtorvald** [comment]
@demget doesn't work for some reason. I guess it's because the first line serves files from within: ./web/
And with the broccoli example it serves / where it contains web/ (if you understand correctly).
INFO[0000] &{map[web/index.html:0xc0001768c0] [web/index.html]} 
Although that should mean /web/index.html would work but I also get a NRE. Is there a way to get more verbosity for debugging? I'm too tired now, will look at it with a clear mind later on. Thanks for the fix this far.

**Comment by jtorvald** [comment]
@demget I tested it and can't get it to work. I attached a example written for this use case.
It shows web/index.html in the filesystem but the http server can't find it on /index.html and web/index.html
[broccoli-issue2.zip](https://github.com/aletheia-icu/broccoli/files/4502154/broccoli-issue2.zip)
And I've been thinking, if it would be possible to do a broccoli.GetRoot("/web/") and get a broccoli object with the contents of /web/ as the root of the filesystem.

**Comment by demget** [comment]
@jtorvald Please check out new v1.0.3 release. And you still have a [syntax mistake](https://github.com/aletheia-icu/broccoli/issues/2#issuecomment-615252910) after `-include` flag.

Use this to serve the files inside `web` directory:
```go
http.ListenAndServe(":8080", broccoli.Serve("web"))
```

**Comment by jtorvald** [comment]
@demget  sorry I missed your previous comment about the -include flag. This works! Thanks a lot.

**Comment by curio77** [comment]
For me, the status quo after the changes is sufficiently flexible to satisfy my original complaint. Thanks!

**Comment by demget** [comment]
Fixed. https://github.com/aletheia-icu/broccoli/commit/2b30082a017ff7eaf5dfe5afa66930a5b26cc2b3
